### ISSUE TITLE
哈啰单车需要修正下

### ISSUE THREAD

**Issue by PingZi-Wing** [Sliverkiss/QuantumultX#10]
目前哈啰单车关联的链接是gist的老版本，会找不到token来源链接，应该是https://gist.githubusercontent.com/Sliverkiss/4e0081f7b18a2cea9dbdf13545e60885/raw/hldc.js
另外上述链接中针对Loon的token脚本缺少requires-body=true参数，应该是
http-request ^https:\/\/api\.hellobike\.com\/api\?user\.taurus\.pointInfo script-path=https://gist.githubusercontent.com/Sliverkiss/4e0081f7b18a2cea9dbdf13545e60885/raw/hldc.js, requires-body=true, timeout=60, tag=哈啰单车获取token

**Comment by Sliverkiss** [comment]
> 目前哈啰单车关联的链接是gist的老版本，会找不到token来源链接，应该是https://gist.githubusercontent.com/Sliverkiss/4e0081f7b18a2cea9dbdf13545e60885/raw/hldc.js
> 
> 另外上述链接中针对Loon的token脚本缺少requires-body=true参数，应该是
> 
> http-request ^https:\/\/api\.hellobike\.com\/api\?user\.taurus\.pointInfo script-path=https://gist.githubusercontent.com/Sliverkiss/4e0081f7b18a2cea9dbdf13545e60885/raw/hldc.js, requires-body=true, timeout=60, tag=哈啰单车获取token

已更新脚本，内容如下：
- 代码开源，修复并增加奖励金系列任务
- 更换获取ck链接及ck格式，需要清空boxjs变量重新获取。
