### ISSUE TITLE
棒约翰签到可兑换小吃披萨

### ISSUE THREAD

**Issue by th2006464** [Sliverkiss/QuantumultX#13]
希望可以新增棒约翰签到，积分可以兑换小吃披萨券还有DQ的餐食。
每天签到5积分，7天额外15积分。
签到路径：
微信棒约翰点单小程序，下方商城，最上面签到。

**Comment by Sliverkiss** [comment]
> 希望可以新增棒约翰签到，积分可以兑换小吃披萨券还有DQ的餐食。
> 
> 每天签到5积分，7天额外15积分。
> 
> 签到路径：
> 
> 微信棒约翰点单小程序，下方商城，最上面签到。

https://raw.githubusercontent.com/Sliverkiss/GoodNight/master/Script/cfb.js
