### ISSUE TITLE
naixue add-on添加失败

### ISSUE THREAD

**Issue by OpenWaygate** [Sliverkiss/QuantumultX#7]
naixue add-on添加失败

Invalid Line ^https:\/\/tm-web\.pin-dao\.cn\/user\/base-userinfo script-request-body https://gist.githubusercontent.com/Sliverkiss/4d0e9572b99530b7cb0e7298622aa2a9/raw/naixue.js

**Comment by Sliverkiss** [comment]
qx语法错误，不会用就别强求了

**Comment by Sliverkiss** [comment]
收到，已修复。
